@startuml Architecture

package "Domain"
{
    package "PodchanContainerDomain"
    { 
        package "ValueObject"
        {
            class PodchanContainerId
            class PodchanContainerName
            class PodchanContainerConfig
            {
                self,
                image: str
                ' 開発段階では未実装
                ' env: list[str]
                ' ports: list[str]
                ' volumes: list[str]
                ' restart: str
            }
            interface PodchanContainerStatus
            {
                ' 設定値の変更が可能か
                is_change_config() -> bool
                ' 名称の変更が可能か
                is_change_name() -> bool
            }
            ' 実行中
            class RunningStatus
            ' 停止中
            class StoppedStatus

            PodchanContainerStatus <-- RunningStatus
            PodchanContainerStatus <-- StoppedStatus

            note right of "PodchanContainerId"
            PodchanのコンテナのID
            end note
            note right of "PodchanContainerName"
            Podchanのコンテナの名称
            end note
            note right of "PodchanContainerConfig"
            Podchanのコンテナの設定値
            end note
            note right of "PodchanContainerStatus"
            Podchanのコンテナの状態
            is_change_configで設定値の変更可否を返す
            end note
        }

        package "Entity"
        {
            class PodchanContainer
            {
                __init__( id : PodchanContainerId , config: PodchanContainerConfig )
                change_name( config: PodchanContainerName )
                change_status( status : PodchanContainerStatus )
                change_config( config: PodchanContainerConfig )
            }

            PodchanContainer ..> PodchanContainerId
            PodchanContainer ..> PodchanContainerName
            PodchanContainer ..> PodchanContainerConfig
            PodchanContainer ..> PodchanContainerStatus

            note right of "PodchanContainer"
            Podchanのコンテナの状態を保持し、状態ごとの
            ルールに基づいてconfigの修正を行う
            end note
        }

        package "Repository"
        {
            interface PodchanContainerRepository
            {
                __init__()
                save( container : PodchanContainer )
                delete( id : PodchanContainerId ) -> PodchanContainer
                exists() -> bool
                find( id : PodchanContainerId ) -> PodchanContainer
                find_all() -> List[PodchanContainer]
            }

            PodchanContainerRepository ..> PodchanContainer
            PodchanContainerRepository ..> PodchanContainerId

            note right of "PodchanContainerRepository"
            Podchanのコンテナを保持するインターフェース
            end note
        }

        package "Runtime"
        {
            abstract PodchanContainerRuntime
            {
                start( container : PodchanContainer )
                stop( container : PodchanContainer )
                sync( container : PodchanContainer )
            }

            PodchanContainerRuntime ..> PodchanContainer

            note right of "PodchanContainerRuntime"
            Podchanのコンテナを操作するRuntime
            end note
        }

        package "OperatorEvent"
        {
            ' PodchanContainerOperatorのイベント
            interface PodchanContainerOperatorEvent
            ' 開始後に発行されるイベント
            class PodchanContainerOperatorStartedEvent
            ' 停止後に発行されるイベント
            class PodchanContainerOperatorStopedEvent

            ' イベントを取得するリスナー
            class PodchanContainerOperatorEventListener
            {
                on_event( event : PodchanContainerOperatorEvent )
            }

            PodchanContainerOperatorEvent <-- PodchanContainerStartedEvent
            PodchanContainerOperatorEvent <-- PodchanContainerStopedEvent

            note right of "PodchanContainerOperatorEvent"
            PodchanContainerOperatorのイベント
            end note
            note right of "PodchanContainerOperatorEventListener"
            イベントを取得するリスナー
            end note
        }

        package "Operator"
        {
            class PodchanContainerOperator
            {
                __init__( container : PodchanContainer , runtime: PodchanContainerRuntime )
                start()
                stop()
                sync()
                subscribe( listener: PodchanContainerOperatorEventListener )
                unsubscribe( listener: PodchanContainerOperatorEventListener )
            }

            PodchanContainerOperator ..> PodchanContainer
            PodchanContainerOperator ..> PodchanContainerRuntime
            PodchanContainerOperator ..> PodchanContainerOperatorEvent
            PodchanContainerOperator ..> PodchanContainerOperatorEventListener

            note right of "PodchanContainerOperator"
            Podchanのコンテナを操作するDomain Operator
            end note
        }
    }
}

package "Infrastructure"
{
    package Podman
    {
        class PodmanContainerRuntime
        PodchanContainerRuntime <-- PodmanContainerRuntime

        note right of "PodmanContainerRuntime"
        Domain側の抽象を実装して
        InfrastructureとしてPodmanを叩く層
        end note
    }
    package InMemory
    {
        class PodchanContainerInMemoryRepository
        PodchanContainerRepository <-- PodchanContainerInMemoryRepository

        note right of "PodmanContainerRuntime"
        Domain側の抽象を実装して
        InfrastructureとしてPodmanを叩く層
        end note
    }
}

' 現在は実装しない
package "Application"
{
    package "PodchanContainerApplication"
    {
        package "DataTransferObject"
        {
            class PodchanContainerData
            {
                ' このクラスはApplicaitonEventListnerが受け取る値にしたい（ドメインをラッパーする目的）
                __init__( container : PodchanContainer )
                get_id()
                get_name()
                get_image()
            }
            PodchanContainerData ..> PodchanContainer

            note right of "PodchanContainerData"
            Podchanのドメインを外に出さない境界を果たすクラス
            Id,Name,ConfigをラッパーしてApplicationの外に伝えないようにする
            end note
        }

        package "ApplicaitonEvent"
        {
            ' PodchanContainerOperatorのイベント
            abstract PodchanContainerApplicaitonEvent
            ' 開始後に発行されるイベント
            class PodchanContainerStartedEvent
            {
                __init__( container : PodchanContainer )
                get_container_data() -> PodchanContainerData
            }
            ' 停止後に発行されるイベント
            class PodchanContainerStopedEvent
            {
                __init__( container : PodchanContainer )
                get_container_data() -> PodchanContainerData
            }

            ' イベントを取得するリスナー
            abstract PodchanContainerApplicaitonEventListener
            {
                on_event( event : PodchanContainerApplicaitonEvent )
            }

            PodchanContainerApplicaitonEvent <-- PodchanContainerStartedEvent
            PodchanContainerData <.. PodchanContainerStartedEvent
            PodchanContainerApplicaitonEvent <-- PodchanContainerStopedEvent
            PodchanContainerData <.. PodchanContainerStopedEvent
            PodchanContainerApplicaitonEvent ..> PodchanContainerApplicaitonEvent

            note right of "PodchanContainerApplicaitonEvent"
            PodchanContainerApplicationのイベント
            end note
            note right of "PodchanContainerApplicaitonEventListener"
            イベントを取得するリスナー
            end note
        }

        package "ApplicaitonCommand"
        {
            class PodchanContainerApplicationRegistCommand
            {
                __init__(container_id: str,name: str, image: str)
            }
            class PodchanContainerApplicationDeleteCommand
            {
                __init__(container_id: str)
            }
            class PodchanContainerApplicationStartCommand
            {
                __init__(container_id: str)
            }
            class PodchanContainerApplicationStopCommand
            {
                __init__(container_id: str)
            }
            class PodchanContainerApplicationUpdateCommand
            {
                __init__(container_id: str)
            }
        }
        note right of "ApplicaitonCommand"
        Applicationを使用する（ユースケース）場合のコマンド
        end note

        package "Applicaiton"
        {
            class PodchanContainerApplicationEventPublisher
            {
                __init__( repository : PodchanContainerRepository )
                on_event( event: PodchanContainerOperatorEvent )
                subscribe( listener: PodchanContainerApplicaitonEventListener )
                unsubscribe( listener: PodchanContainerApplicaitonEventListener )
            }
            PodchanContainerApplicationEventPublisher --|> PodchanContainerOperatorEventListener
            PodchanContainerApplicationEventPublisher ..> PodchanContainerApplicaitonEvent
            PodchanContainerApplicationEventPublisher ..> PodchanContainerApplicaitonEventListener
            PodchanContainerApplicationEventPublisher ..> PodchanContainerRepository
            
            class PodchanContainerAppliation
            {
                __init__( repository : PodchanContainerRepository , runtime : PodchanContainerRuntime )
                ' 登録
                regist( command : PodchanContainerApplicationRegistCommand )
                ' 削除
                delete( command : PodchanContainerApplicationDeleteCommand )
                ' 起動
                start( command : PodchanContainerApplicationStartCommand )
                ' 停止
                stop( command : PodchanContainerApplicationStopCommand )
                ' 同期
                update( command : PodchanContainerApplicationUpdateCommand )
                ' EventListnerの登録、削除
                subscribe( listener: PodchanContainerApplicaitonEventListener )
                unsubscribe( listener: PodchanContainerApplicaitonEventListener )
            }
            PodchanContainerAppliation ..> "ApplicaitonCommand"
            PodchanContainerAppliation ..> PodchanContainerRepository
            PodchanContainerAppliation ..> PodchanContainerApplicaitonEventListener
            
            note right of "PodchanContainerApplicationEventPublisher"
            OperatorEventからAppliationEventを発行する
            end note
            note right of "PodchanContainerAppliation"
            Containerのユースケースを提供する
            end note
        }
    }
}
    

@enduml